from typing import Literal, TypedDict

import numpy as np
from numpy.typing import NDArray

class RlVecEnv:
    n_envs: int
    n_players: int
    max_planets: int
    max_entities: int
    max_fleets: int
    max_per_planet_launches: int
    min_fleet_size: int

    def __init__(
        self,
        n_envs: int,
        two_player_weight: float = ...,
        obs_spec: str = ...,
        action_spec: str = ...,
        max_entities: int = ...,
        ship_count_one_hot_max: int = ...,
        max_per_planet_launches: int = ...,
        min_fleet_size: int = ...,
        n_bins: int = ...,
        targeting_mode: str = ...,
        reward_mode: str = ...,
    ) -> None: ...
    def reset(
        self,
        planet_obs: np.ndarray,
        orbiting_planet_obs: np.ndarray,
        fleet_obs: np.ndarray,
        comet_obs: np.ndarray,
        entity_mask: np.ndarray,
        still_playing: np.ndarray,
        global_obs: np.ndarray,
        can_act: np.ndarray,
        max_launch: np.ndarray,
        player_features: np.ndarray | None = ...,
        fleet_target: np.ndarray | None = ...,
        target_incoming_features: np.ndarray | None = ...,
    ) -> None: ...
    def reset_discrete_target_bins(
        self,
        planet_obs: np.ndarray,
        orbiting_planet_obs: np.ndarray,
        fleet_obs: np.ndarray,
        comet_obs: np.ndarray,
        entity_mask: np.ndarray,
        still_playing: np.ndarray,
        global_obs: np.ndarray,
        can_act: np.ndarray,
        player_features: np.ndarray | None = ...,
        fleet_target: np.ndarray | None = ...,
        target_incoming_features: np.ndarray | None = ...,
    ) -> None: ...
    def truncate_envs(
        self,
        truncate_mask: np.ndarray,
        planet_obs: np.ndarray,
        orbiting_planet_obs: np.ndarray,
        fleet_obs: np.ndarray,
        comet_obs: np.ndarray,
        entity_mask: np.ndarray,
        still_playing: np.ndarray,
        global_obs: np.ndarray,
        can_act: np.ndarray,
        max_launch: np.ndarray | None = ...,
        player_features: np.ndarray | None = ...,
        fleet_target: np.ndarray | None = ...,
        target_incoming_features: np.ndarray | None = ...,
    ) -> None: ...
    def step(
        self,
        launch: np.ndarray,
        angle: np.ndarray,
        ships: np.ndarray,
        planet_obs: np.ndarray,
        orbiting_planet_obs: np.ndarray,
        fleet_obs: np.ndarray,
        comet_obs: np.ndarray,
        entity_mask: np.ndarray,
        still_playing: np.ndarray,
        global_obs: np.ndarray,
        can_act: np.ndarray,
        max_launch: np.ndarray,
        rewards: np.ndarray,
        dones: np.ndarray,
        player_features: np.ndarray | None = ...,
        fleet_target: np.ndarray | None = ...,
        target_incoming_features: np.ndarray | None = ...,
    ) -> dict[str, list[float]]: ...
    def step_discrete_target_bins(
        self,
        target: np.ndarray,
        fleet_bin: np.ndarray,
        planet_obs: np.ndarray,
        orbiting_planet_obs: np.ndarray,
        fleet_obs: np.ndarray,
        comet_obs: np.ndarray,
        entity_mask: np.ndarray,
        still_playing: np.ndarray,
        global_obs: np.ndarray,
        can_act: np.ndarray,
        rewards: np.ndarray,
        dones: np.ndarray,
        player_features: np.ndarray | None = ...,
        fleet_target: np.ndarray | None = ...,
        target_incoming_features: np.ndarray | None = ...,
    ) -> dict[str, list[float]]: ...
    def step_discrete_targets(
        self,
        launch: np.ndarray,
        target: np.ndarray,
        ships: np.ndarray,
        planet_obs: np.ndarray,
        orbiting_planet_obs: np.ndarray,
        fleet_obs: np.ndarray,
        comet_obs: np.ndarray,
        entity_mask: np.ndarray,
        still_playing: np.ndarray,
        global_obs: np.ndarray,
        can_act: np.ndarray,
        max_launch: np.ndarray,
        rewards: np.ndarray,
        dones: np.ndarray,
        player_features: np.ndarray | None = ...,
        fleet_target: np.ndarray | None = ...,
        target_incoming_features: np.ndarray | None = ...,
    ) -> dict[str, list[float]]: ...
    def obs_shapes(
        self,
    ) -> (
        tuple[
            tuple[int, int, int],
            tuple[int, int],
            tuple[int, int, int],
            tuple[int, int, int],
            tuple[int, int],
            tuple[int, int],
            tuple[int, int],
            tuple[int, ...],
            tuple[int, int, int],
        ]
        | tuple[
            tuple[int, int, int],
            tuple[int, int],
            tuple[int, int, int],
            tuple[int, int, int],
            tuple[int, int],
            tuple[int, int],
            tuple[int, int],
            tuple[int, int, int],
            tuple[int, ...],
            tuple[int, int, int],
        ]
        | tuple[
            tuple[int, int, int],
            tuple[int, int],
            tuple[int, int, int],
            tuple[int, int],
            tuple[int, int, int],
            tuple[int, int, int],
            tuple[int, int],
            tuple[int, int],
            tuple[int, int],
            tuple[int, int, int],
            tuple[int, ...],
            tuple[int, int, int],
        ]
    ): ...
    def state_snapshot(self, env_index: int) -> dict[str, object]: ...
    def terminal_snapshot(self, env_index: int) -> dict[str, object] | None: ...
    def terminal_metrics(self, env_index: int) -> dict[str, float] | None: ...
    def write_action_mask(
        self,
        action_spec: str,
        min_fleet_size: int,
        n_bins: int,
        targeting_mode: str,
        can_act: np.ndarray,
        max_launch: np.ndarray,
    ) -> None: ...
    def write_action_mask_discrete_target_bins(
        self,
        min_fleet_size: int,
        n_bins: int,
        targeting_mode: str,
        can_act: np.ndarray,
    ) -> None: ...
    def write_observation(
        self,
        obs_spec: str,
        action_spec: str,
        max_entities: int,
        ship_count_one_hot_max: int,
        min_fleet_size: int,
        n_bins: int,
        targeting_mode: str,
        planet_obs: np.ndarray,
        orbiting_planet_obs: np.ndarray,
        fleet_obs: np.ndarray,
        comet_obs: np.ndarray,
        entity_mask: np.ndarray,
        still_playing: np.ndarray,
        global_obs: np.ndarray,
        can_act: np.ndarray,
        max_launch: np.ndarray | None,
        player_features: np.ndarray | None = ...,
        fleet_target: np.ndarray | None = ...,
        target_incoming_features: np.ndarray | None = ...,
    ) -> None: ...
    def decode_pure_actions(
        self,
        launch: np.ndarray,
        angle: np.ndarray,
        ships: np.ndarray,
        max_per_planet_launches: int,
        min_fleet_size: int,
        valid: np.ndarray,
        from_planet_id: np.ndarray,
        decoded_angle: np.ndarray,
        decoded_ships: np.ndarray,
    ) -> None: ...
    def decode_discrete_target_actions(
        self,
        launch: np.ndarray,
        target: np.ndarray,
        ships: np.ndarray,
        max_per_planet_launches: int,
        min_fleet_size: int,
        targeting_mode: str,
        valid: np.ndarray,
        from_planet_id: np.ndarray,
        decoded_angle: np.ndarray,
        decoded_ships: np.ndarray,
    ) -> None: ...
    def decode_discrete_target_bin_actions(
        self,
        target: np.ndarray,
        fleet_bin: np.ndarray,
        min_fleet_size: int,
        n_bins: int,
        targeting_mode: str,
        valid: np.ndarray,
        from_planet_id: np.ndarray,
        decoded_angle: np.ndarray,
        decoded_ships: np.ndarray,
    ) -> None: ...
    def step_decoded_actions(
        self,
        valid: np.ndarray,
        from_planet_id: np.ndarray,
        angle: np.ndarray,
        ships: np.ndarray,
        planet_obs: np.ndarray,
        orbiting_planet_obs: np.ndarray,
        fleet_obs: np.ndarray,
        comet_obs: np.ndarray,
        entity_mask: np.ndarray,
        still_playing: np.ndarray,
        global_obs: np.ndarray,
        can_act: np.ndarray,
        max_launch: np.ndarray | None,
        rewards: np.ndarray,
        dones: np.ndarray,
        player_features: np.ndarray | None = ...,
        fleet_target: np.ndarray | None = ...,
        target_incoming_features: np.ndarray | None = ...,
    ) -> dict[str, list[float]]: ...

def assert_release_build() -> None: ...
def rl_obs_constants() -> tuple[int, int, int, int, int, int, int, int, int]: ...
def rl_obs_ext_v2_constants() -> tuple[int, int]: ...
def rl_obs_cross_attn_constants() -> tuple[int, int]: ...
def encode_entity_based(
    planets: np.ndarray,
    initial_planets: np.ndarray,
    fleets: np.ndarray,
    comet_planet_ids: np.ndarray,
    comet_path_indices: np.ndarray,
    comet_path_lengths: np.ndarray,
    comet_paths: np.ndarray,
    angular_velocity: float,
    step: int = ...,
    episode_steps: int = ...,
    max_entities: int = ...,
    min_fleet_size: int = ...,
    ship_count_one_hot_max: int = ...,
    fleet_filter_min_size: int = ...,
) -> tuple[
    np.ndarray,
    np.ndarray,
    np.ndarray,
    np.ndarray,
    np.ndarray,
    np.ndarray,
    np.ndarray,
    np.ndarray,
    np.ndarray,
    int,
]: ...
def encode_entity_based_with_player_features(
    planets: np.ndarray,
    initial_planets: np.ndarray,
    fleets: np.ndarray,
    comet_planet_ids: np.ndarray,
    comet_path_indices: np.ndarray,
    comet_path_lengths: np.ndarray,
    comet_paths: np.ndarray,
    angular_velocity: float,
    step: int = ...,
    episode_steps: int = ...,
    max_entities: int = ...,
    min_fleet_size: int = ...,
    ship_count_one_hot_max: int = ...,
    fleet_filter_min_size: int = ...,
    player_feature_channels: int = ...,
) -> tuple[
    np.ndarray,
    np.ndarray,
    np.ndarray,
    np.ndarray,
    np.ndarray,
    np.ndarray,
    np.ndarray,
    np.ndarray,
    np.ndarray,
    np.ndarray,
    int,
]: ...
def encode_entity_based_cross_attn(
    planets: np.ndarray,
    initial_planets: np.ndarray,
    fleets: np.ndarray,
    comet_planet_ids: np.ndarray,
    comet_path_indices: np.ndarray,
    comet_path_lengths: np.ndarray,
    comet_paths: np.ndarray,
    angular_velocity: float,
    step: int = ...,
    episode_steps: int = ...,
    max_entities: int = ...,
    min_fleet_size: int = ...,
    fleet_filter_min_size: int = ...,
) -> tuple[
    np.ndarray,
    np.ndarray,
    np.ndarray,
    np.ndarray,
    np.ndarray,
    np.ndarray,
    np.ndarray,
    np.ndarray,
    np.ndarray,
    np.ndarray,
    np.ndarray,
    np.ndarray,
    int,
]: ...
def pure_actions_to_kaggle(
    planets: np.ndarray,
    initial_planets: np.ndarray,
    fleets: np.ndarray,
    comet_planet_ids: np.ndarray,
    comet_path_indices: np.ndarray,
    comet_path_lengths: np.ndarray,
    comet_paths: np.ndarray,
    angular_velocity: float,
    step: int,
    episode_steps: int,
    player: int,
    launch: np.ndarray,
    angle: np.ndarray,
    ships: np.ndarray,
    max_per_planet_launches: int,
    min_fleet_size: int,
) -> list[list[float]]: ...
def discrete_target_actions_to_kaggle(
    planets: np.ndarray,
    initial_planets: np.ndarray,
    fleets: np.ndarray,
    comet_planet_ids: np.ndarray,
    comet_path_indices: np.ndarray,
    comet_path_lengths: np.ndarray,
    comet_paths: np.ndarray,
    angular_velocity: float,
    step: int,
    episode_steps: int,
    player: int,
    launch: np.ndarray,
    target: np.ndarray,
    ships: np.ndarray,
    max_per_planet_launches: int,
    min_fleet_size: int,
    targeting_mode: str = ...,
) -> list[list[float]]: ...
def discrete_target_bin_actions_to_kaggle(
    planets: np.ndarray,
    initial_planets: np.ndarray,
    fleets: np.ndarray,
    comet_planet_ids: np.ndarray,
    comet_path_indices: np.ndarray,
    comet_path_lengths: np.ndarray,
    comet_paths: np.ndarray,
    angular_velocity: float,
    step: int,
    episode_steps: int,
    player: int,
    target: np.ndarray,
    fleet_bin: np.ndarray,
    min_fleet_size: int,
    n_bins: int,
    targeting_mode: str = ...,
) -> list[list[float]]: ...
def encode_kaggriculture_headers_into(
    headers: str,
    *,
    tile_kind: NDArray[np.int64],
    tile_crop: NDArray[np.int64],
    tile_animal: NDArray[np.int64],
    tile_cell: NDArray[np.int64],
    tile_role: NDArray[np.int64],
    tiles_int: NDArray[np.int64],
    tiles_float: NDArray[np.float32],
    actor_slot: NDArray[np.int64],
    actor_cell: NDArray[np.int64],
    actor_role: NDArray[np.int64],
    actor_mask: NDArray[np.bool_],
    actor_inventory: NDArray[np.int64],
    actor_inventory_rank: NDArray[np.int64],
    actors_float: NDArray[np.float32],
    player_features: NDArray[np.float32],
    storage_counts: NDArray[np.int64],
    storage_rank: NDArray[np.int64],
    banks: NDArray[np.float64],
    shop_type: NDArray[np.int64],
    shop_slot: NDArray[np.int64],
    shop_mask: NDArray[np.bool_],
    market_product: NDArray[np.int64],
    market_float: NDArray[np.float32],
    market_int: NDArray[np.int64],
    global_features: NDArray[np.float32],
    globals_int: NDArray[np.int64],
    still_playing: NDArray[np.bool_],
    order_limits: NDArray[np.int64],
    can_act: NDArray[np.bool_],
) -> None: ...

class KaggricultureRewardDict(TypedDict):
    reward_mode: Literal["win_loss"]
    econ_shaping: float
    econ_starvation_weight: float
    econ_drought_weight: float
    econ_cap: float
    econ_ineffective_weight: float
    econ_ineffective_cap: float
    econ_bank_weight: float
    econ_bank_scale: float
    econ_bank_cap: float

class KaggricultureTerminalMetrics(TypedDict):
    bank_0: float
    bank_1: float
    margin_0: float
    episode_steps: int
    winner: Literal[-1, 0, 1]
    econ_0: NDArray[np.int64]
    econ_1: NDArray[np.int64]

class KaggricultureEnv:
    def __init__(
        self,
        n_envs: int,
        seed: int,
        seed_stride: int,
        config: str,
        reward_config: KaggricultureRewardDict,
        native_threads: int,
        *,
        hire_limit: int,
    ) -> None: ...
    def observe(
        self,
        *,
        tile_kind: NDArray[np.int64],
        tile_crop: NDArray[np.int64],
        tile_animal: NDArray[np.int64],
        tile_cell: NDArray[np.int64],
        tile_role: NDArray[np.int64],
        tiles_int: NDArray[np.int64],
        tiles_float: NDArray[np.float32],
        actor_slot: NDArray[np.int64],
        actor_cell: NDArray[np.int64],
        actor_role: NDArray[np.int64],
        actor_mask: NDArray[np.bool_],
        actor_inventory: NDArray[np.int64],
        actor_inventory_rank: NDArray[np.int64],
        actors_float: NDArray[np.float32],
        player_features: NDArray[np.float32],
        storage_counts: NDArray[np.int64],
        storage_rank: NDArray[np.int64],
        banks: NDArray[np.float64],
        shop_type: NDArray[np.int64],
        shop_slot: NDArray[np.int64],
        shop_mask: NDArray[np.bool_],
        market_product: NDArray[np.int64],
        market_float: NDArray[np.float32],
        market_int: NDArray[np.int64],
        global_features: NDArray[np.float32],
        globals_int: NDArray[np.int64],
        still_playing: NDArray[np.bool_],
        order_limits: NDArray[np.int64],
        can_act: NDArray[np.bool_],
        rewards: NDArray[np.float32],
        dones: NDArray[np.bool_],
        transition_banks_before: NDArray[np.float64],
        transition_banks_after: NDArray[np.float64],
        transition_econ_before: NDArray[np.int64],
        transition_econ_after: NDArray[np.int64],
    ) -> None: ...
    def reset(
        self,
        *,
        tile_kind: NDArray[np.int64],
        tile_crop: NDArray[np.int64],
        tile_animal: NDArray[np.int64],
        tile_cell: NDArray[np.int64],
        tile_role: NDArray[np.int64],
        tiles_int: NDArray[np.int64],
        tiles_float: NDArray[np.float32],
        actor_slot: NDArray[np.int64],
        actor_cell: NDArray[np.int64],
        actor_role: NDArray[np.int64],
        actor_mask: NDArray[np.bool_],
        actor_inventory: NDArray[np.int64],
        actor_inventory_rank: NDArray[np.int64],
        actors_float: NDArray[np.float32],
        player_features: NDArray[np.float32],
        storage_counts: NDArray[np.int64],
        storage_rank: NDArray[np.int64],
        banks: NDArray[np.float64],
        shop_type: NDArray[np.int64],
        shop_slot: NDArray[np.int64],
        shop_mask: NDArray[np.bool_],
        market_product: NDArray[np.int64],
        market_float: NDArray[np.float32],
        market_int: NDArray[np.int64],
        global_features: NDArray[np.float32],
        globals_int: NDArray[np.int64],
        still_playing: NDArray[np.bool_],
        order_limits: NDArray[np.int64],
        can_act: NDArray[np.bool_],
        rewards: NDArray[np.float32],
        dones: NDArray[np.bool_],
        transition_banks_before: NDArray[np.float64],
        transition_banks_after: NDArray[np.float64],
        transition_econ_before: NDArray[np.int64],
        transition_econ_after: NDArray[np.int64],
    ) -> None: ...
    def step(
        self,
        tokens: NDArray[np.int64],
        lengths: NDArray[np.int64],
        *,
        tile_kind: NDArray[np.int64],
        tile_crop: NDArray[np.int64],
        tile_animal: NDArray[np.int64],
        tile_cell: NDArray[np.int64],
        tile_role: NDArray[np.int64],
        tiles_int: NDArray[np.int64],
        tiles_float: NDArray[np.float32],
        actor_slot: NDArray[np.int64],
        actor_cell: NDArray[np.int64],
        actor_role: NDArray[np.int64],
        actor_mask: NDArray[np.bool_],
        actor_inventory: NDArray[np.int64],
        actor_inventory_rank: NDArray[np.int64],
        actors_float: NDArray[np.float32],
        player_features: NDArray[np.float32],
        storage_counts: NDArray[np.int64],
        storage_rank: NDArray[np.int64],
        banks: NDArray[np.float64],
        shop_type: NDArray[np.int64],
        shop_slot: NDArray[np.int64],
        shop_mask: NDArray[np.bool_],
        market_product: NDArray[np.int64],
        market_float: NDArray[np.float32],
        market_int: NDArray[np.int64],
        global_features: NDArray[np.float32],
        globals_int: NDArray[np.int64],
        still_playing: NDArray[np.bool_],
        order_limits: NDArray[np.int64],
        can_act: NDArray[np.bool_],
        rewards: NDArray[np.float32],
        dones: NDArray[np.bool_],
        transition_banks_before: NDArray[np.float64],
        transition_banks_after: NDArray[np.float64],
        transition_econ_before: NDArray[np.int64],
        transition_econ_after: NDArray[np.int64],
    ) -> dict[str, list[float]]: ...
    def truncate_envs(
        self,
        mask: NDArray[np.bool_],
        *,
        tile_kind: NDArray[np.int64],
        tile_crop: NDArray[np.int64],
        tile_animal: NDArray[np.int64],
        tile_cell: NDArray[np.int64],
        tile_role: NDArray[np.int64],
        tiles_int: NDArray[np.int64],
        tiles_float: NDArray[np.float32],
        actor_slot: NDArray[np.int64],
        actor_cell: NDArray[np.int64],
        actor_role: NDArray[np.int64],
        actor_mask: NDArray[np.bool_],
        actor_inventory: NDArray[np.int64],
        actor_inventory_rank: NDArray[np.int64],
        actors_float: NDArray[np.float32],
        player_features: NDArray[np.float32],
        storage_counts: NDArray[np.int64],
        storage_rank: NDArray[np.int64],
        banks: NDArray[np.float64],
        shop_type: NDArray[np.int64],
        shop_slot: NDArray[np.int64],
        shop_mask: NDArray[np.bool_],
        market_product: NDArray[np.int64],
        market_float: NDArray[np.float32],
        market_int: NDArray[np.int64],
        global_features: NDArray[np.float32],
        globals_int: NDArray[np.int64],
        still_playing: NDArray[np.bool_],
        order_limits: NDArray[np.int64],
        can_act: NDArray[np.bool_],
        rewards: NDArray[np.float32],
        dones: NDArray[np.bool_],
        transition_banks_before: NDArray[np.float64],
        transition_banks_after: NDArray[np.float64],
        transition_econ_before: NDArray[np.int64],
        transition_econ_after: NDArray[np.int64],
    ) -> None: ...
    def terminal_metrics(
        self, env_index: int
    ) -> KaggricultureTerminalMetrics | None: ...
    def state_snapshot(self, env_index: int) -> str: ...
    def seed_state(self) -> tuple[int, tuple[int, ...]]: ...

def kaggriculture_encode(
    action_json: str,
    actors: int,
    order_limit: int,
    hire_limit: int,
    out: NDArray[np.int64],
) -> int: ...
def kaggriculture_decode(
    tokens: NDArray[np.int64],
    length: int,
    actors: int,
    order_limit: int,
    hire_limit: int,
) -> str: ...
def kaggriculture_grammar_tables() -> dict[str, NDArray[np.bool_]]: ...
def kaggriculture_grammar_constants() -> tuple[
    int, tuple[str, ...], tuple[int, ...]
]: ...
