[package]
name = "kaggriculture-opponents"
version = "0.1.0"
edition = "2024"

[dependencies]
indexmap = "2.11"
kaggriculture-engine = { version = "0.1.0", path = "../engine_rs" }
num-bigint = "0.4"
num-traits = "0.2"
serde_json = { version = "1.0.151", features = ["arbitrary_precision", "preserve_order"] }

[dev-dependencies]
sha2 = "0.10"
