from pathlib import Path
import hashlib,json,subprocess,time
root=Path.cwd()
work=root/'ops/rebuild-2026-09-29/codex/verify-7.1-r2'
out=work/'regeneration'
(out/'oracle').mkdir(parents=True,exist_ok=True)
(out/'replay').mkdir(parents=True,exist_ok=True)
python='/Users/poonszesen/kaggriculture/.venv/bin/python'
base=[python,'scripts/kaggriculture_parity/generate_traces.py']
for i in (0,2,4,6):
    command=base+['--preset','opponents','--opponent-start',str(i),'--games','2','--out',str(out/'oracle'),'--manifest','--summary',str(out/f'games-{i}.json')]
    started=time.monotonic()
    with (out/f'games-{i}.log').open('w') as log:
        result=subprocess.run(command,stdout=log,stderr=subprocess.STDOUT)
    assert result.returncode==0,(i,result.returncode)
    print('generated',i,'seconds',round(time.monotonic()-started,2),flush=True)
command=base+['--preset','opponent-replay','--oracle-dir',str(out/'oracle'),'--out',str(out/'replay'),'--summary',str(out/'replay-summary.json')]
with (out/'replay.log').open('w') as log:
    result=subprocess.run(command,stdout=log,stderr=subprocess.STDOUT)
assert result.returncode==0,result.returncode
checks=[]
for kind in ('oracle','replay'):
    for src in sorted((root/'opponents_rs/fixtures'/kind).iterdir()):
        dest=out/kind/src.name
        equal=src.read_bytes()==dest.read_bytes()
        checks.append({'path':str(src.relative_to(root)),'equal':equal,'sha256':hashlib.sha256(dest.read_bytes()).hexdigest(),'bytes':dest.stat().st_size})
        assert equal,src
(out/'byte-comparison.json').write_text(json.dumps(checks,indent=2)+'\n')
print('All',len(checks),'oracle/replay files regenerated byte-exact',flush=True)
