from pathlib import Path
import difflib, hashlib, json, subprocess

pin = '65f0eac5bb00b18a9d3acce319c2a231cbd5dff0'
prefix = 'engine_rs/'
kept = {'Cargo.toml', 'Cargo.lock', 'LICENSE', 'VENDORED_FROM.md', 'src/lib.rs',
        'src/py_random.rs', 'src/econ_attrib.rs', 'tests/py_random.rs'}
kept |= {f'fixtures/episode-{i}.jsonl.gz' for i in (95324500, 95901360, 95921764, 95990191)}
why_edit = {
    'src/lib.rs': 'Remove only excluded module declarations at reference lines 19, 21-25, 27; see brief dependency table.',
    'Cargo.toml': 'Remove unused cdylib, re_engine binary and Rayon dependency; preserve numeric features and compatibility metadata.',
    'Cargo.lock': 'Generated by cargo remove --offline rayon; prune only unused Rayon dependency closure, no manual edits.',
    'VENDORED_FROM.md': 'Append current trim scope while preserving all historical provenance bytes.',
}
excluded_sources = {
    'ffi': 'C5 C ABI/ctypes replaced by native adapter in Task 1.4',
    'joint_matching': 'C2 policy matching enumeration is outside rules kernel',
    'myolie_features': 'C4 flat v2 encoder rebuilt in Task 1.3',
    'myolie_sampler': 'C3 grammar port after review in Task 1.2',
    'native_agents': 'C2 scripted opponents deferred to selected Phase 7 imports',
    'policy_rows': 'C2 policy action-row machinery is outside rules kernel',
    'training': 'C5 old training lifecycle/collector rebuilt in Task 1.4',
    'main': 'Replay/benchmark CLI excluded; direct replay integration test replaces test purpose',
}
def exclusion(path):
    if path.startswith('src/native_agents/'):
        return excluded_sources['native_agents']
    if path.startswith('src/bin/') or path.startswith('examples/'):
        return 'C2 bot executable/oracle not required for rules transitions'
    if path.startswith('src/') and Path(path).stem in excluded_sources:
        return excluded_sources[Path(path).stem]
    if path.startswith('fixtures/'):
        return 'Bot/controller/matching oracle unused by retained rules and RNG tests'
    if path == 'tests/shoprouter_parity.rs':
        return 'Requires excluded ShopRouterController; tests controller actions, zero engine transitions'
    if path == 'README.md':
        return 'Describes excluded full engine/ABI/matching surfaces and unavailable sibling tools'
    if path == 'V3_IMPORT.json':
        return 'Full prior import manifest superseded by exhaustive TRIM_MANIFEST.json'
    raise ValueError(f'unclassified reference path: {path}')
sha = lambda data: hashlib.sha256(data).hexdigest()
paths = subprocess.check_output(['git', 'ls-tree', '-r', '--name-only', pin, 'engine_rs'], text=True).splitlines()
manifest = dict(schema_version=1, reference_commit=pin, retained=[], excluded=[], authored=[])
for path in paths:
    relative = path.removeprefix(prefix)
    before = subprocess.check_output(['git', 'show', f'{pin}:{path}'])
    if relative not in kept:
        manifest['excluded'].append(dict(path=path, reference_sha256=sha(before), reason=exclusion(relative)))
        continue
    after = Path(path).read_bytes()
    edits = []
    if before != after:
        reason = why_edit[relative]  # Deliberately fail for an unauthorized edited file.
        a = before.decode('utf-8').splitlines(keepends=True)
        b = after.decode('utf-8').splitlines(keepends=True)
        for tag, i, j, x, y in difflib.SequenceMatcher(a=a, b=b, autojunk=False).get_opcodes():
            if tag != 'equal':
                edits.append(dict(start_line=i+1, delete_lines=j-i, insert=''.join(b[x:y]), reason=reason))
    manifest['retained'].append(dict(path=path, reference_sha256=sha(before), sha256=sha(after), edits=edits))
new = Path('engine_rs/tests/replay_parity.rs')
if new.exists():
    manifest['authored'].append(dict(path=new.as_posix(), sha256=sha(new.read_bytes()),
                                     reason='New direct native-reset official-trace parity and comparator regressions'))
assert len(paths) == 125 and len(manifest['retained']) == 12 and len(manifest['excluded']) == 113
manifest['non_engine_changes'] = [
    dict(path='rustfmt.toml', reason='Exclude exactly two immutable vendored sources with known upstream formatting drift; their bytes are checked by provenance manifest.'),
    dict(path='scripts/check_engine_trim.py', reason='Python provenance checker required by Claude review; replaces planned Node tool.'),
    dict(path='tests/tools/test_check_engine_trim.py', reason='Test-first pytest coverage for provenance and inventory drift.'),
    dict(path='justfile', reason='Separate engine manifest-path fmt/check, clippy and test invocations under rs-prepare and prepare; preserve feature isolation.'),
    dict(path='docs/rules-parity-coverage.md', reason='Document current Kaggriculture replay and unit coverage without changing Orbit coverage.'),
    dict(path='cookbook/decisions/restart-the-port-from-isaiahs-clean-base.md', reason='Record completed reviewed trim, verified scope and remaining integration limits.'),
    dict(path='cookbook/decisions/index.md', reason='Reconcile current restart Decision description.'),
    dict(path='cookbook/log.md', reason='Prepend material Task 1.1 adaptation record.'),
    dict(path='ops/rebuild-2026-09-29/1.1', reason='Directory of source-bound command receipts, test-first failures, preserved dirty bytes and result inventory.'),
]
Path('engine_rs/TRIM_MANIFEST.json').write_text(json.dumps(manifest, indent=2) + '\n')
